# 데이터 구조의 이해 (1) - 차원과 배열-1

In [76]:
# 라이브러리를 임포트합니다.
import numpy as np

### 2-1D 배열

In [77]:
# 하나의 행으로 벡터를 만듭니다.
vector_row = np.array([1, 2, 3])

In [78]:
vector_row

array([1, 2, 3])

In [79]:
# 하나의 열로 벡터를 만듭니다.
vector_column = np.array([[1],
                          [2],
                          [3]])

In [80]:
vector_column

array([[1],
       [2],
       [3]])

In [81]:
# 넘파이 배열의 클래스를 출력합니다.
print(type(vector_row))

<class 'numpy.ndarray'>


### 3- 2D 배열

In [82]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [83]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [84]:
# 모두 0으로 채워줌

zero_matrix = np.zeros((3, 2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [85]:
# 모두 1으로 채워줌

one_matrix = np.ones((3, 2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 4- 배열 정보 확인

In [86]:
# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# 행렬의 크기를 확인합니다.
matrix.shape

(3, 4)

In [87]:
# 행렬의 원소 개수를 확인합니다(행 * 열).
matrix.size

12

In [88]:
# 차원 수를 확인합니다.
matrix.ndim

2

In [89]:
# 원소의 데이터 타입을 확인합니다.
print(matrix.dtype)

int32


In [90]:
# 모든 원소에 100을 더합니다.
matrix + 100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

### 5- 배열 크기 변경

In [91]:
# 라이브러리를 임포트합니다.
import numpy as np

# 4x3 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# 2x6 행렬로 크기를 바꿉니다.
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [92]:
matrix.size

12

In [93]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [94]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 6- 배열 전치

In [97]:
# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 행렬을 전치합니다.
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [98]:
# 벡터를 전치합니다.
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [99]:
# 행 벡터를 전치합니다.
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 7- 행렬 펼치기

In [100]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 행렬을 펼칩니다.
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

-------------------------

# 데이터 구조의 이해 (1): 차원과 배열-2

In [102]:
import numpy as np
from IPython.display import Image

In [103]:
# 하나의 행으로 벡터를 만듭니다.
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [104]:
# 하나의 열로 벡터를 만듭니다.
b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [105]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [106]:
a.shape

(3,)

In [107]:
b.shape

(3, 1)

In [108]:
a1 = np.arange(1, 13)  # numbers 1 to 12
a1.shape

(12,)

## 2- 2D 배열

In [109]:
a = np.array([[1, 2],
            [1, 2],
            [1, 2]])
a

array([[1, 2],
       [1, 2],
       [1, 2]])

In [110]:
a_0 = np.zeros((3, 2))
a_0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [111]:
a_1 = np.ones((3, 2))
a_1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## 3- 배열 정보 확인

In [112]:
a.shape

(3, 2)

In [113]:
a_0.shape

(3, 2)

In [114]:
a_1.shape

(3, 2)

In [115]:
a.ndim

2

In [116]:
a_0.ndim

2

In [117]:
a.dtype

dtype('int32')

In [118]:
a_1.dtype

dtype('float64')

In [119]:
a_0.dtype

dtype('float64')

## 4- reshape( ) 배열 바꾸기

In [120]:
a1_2d = a1.reshape(3, 4)  # 3_4
a1_2d.shape

(3, 4)

In [121]:
a1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
a1.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
  # same as above: a1.reshape(3, 4)
a1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
a1.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
  # same as above: a1.reshape(3, 4)
a1.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [126]:
a1.reshape(2, -1)  # same as above: a1.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## 5- reshape( ) 다른 방향으로

In [127]:
a1.reshape(3, 4) # reshapes or ‘fills in’ row by row

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
a1.reshape(3, 4, order='C') # same results as above

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
a1.reshape(3, 4, order='F')  # reshapes column by column

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [130]:
a1  # what's the shape?

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [131]:
a1.shape

(12,)

In [132]:
a1_1_by_12 = a1.reshape(1, -1)  # reshape to 1_12
a1_1_by_12

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [133]:
a1_1_by_12.shape  # 1_12 array

(1, 12)

## 6- Flatten( ), ravel( )로 1D arrays 사용

In [134]:
a1_2d  # 3_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [135]:
a1_2d.ravel()  # ravel by row (default order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [136]:
a1_2d.ravel(order='F')  # ravel by column

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

## 7- Concatenate/stack을 위한 np.stack( ) & np.hstack( )

In [137]:
a1 = np.arange(1, 13)
a2 = np.arange(13, 25)

In [138]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [139]:
a2

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [140]:
stack0 = np.stack((a1, a1, a2, a2))  # default stack along 0th axis
stack0.shape

(4, 12)

In [141]:
stack1 = np.stack((a1, a1, a2, a2), axis=1)
stack1.shape

(12, 4)

In [142]:
stack_long = np.hstack((a1, a2))
stack_long.shape

(24,)

## 8- 3차원 배열 만들기

In [143]:
a1 = np.arange(1, 13).reshape(3, -1)  # 3_4
a2 = np.arange(13, 25).reshape(3, -1)  # 3_4

In [144]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [146]:
a3_0 = np.stack((a1, a2))  # default axis=0 (dimension 0)
a3_1 = np.stack((a1, a2), axis=1)  # along dimension 1
a3_2 = np.stack((a1, a2), axis=2)  # along dimension 2

In [147]:
a3_0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [148]:
a3_1

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [149]:
a3_2

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

## 9- 배열의 차원 인덱싱

In [150]:
# solutions
a3_0[0, :, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
a3_0[0]  # same as above

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [152]:
a3_1[:, 0, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [153]:
a3_2[:, :, 0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 10- flatten( ), ravel( ) 배열 펼치기

In [154]:
a3_0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [155]:
a3_0.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [156]:
a3_0.ravel(order='F')

array([ 1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10, 22,  3, 15,  7, 19, 11,
       23,  4, 16,  8, 20, 12, 24])

In [157]:
a3_0.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [158]:
a3_0.flatten(order='F')

array([ 1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10, 22,  3, 15,  7, 19, 11,
       23,  4, 16,  8, 20, 12, 24])

## 11- reshape( )로 3차원 바꾸기

In [159]:
a3_0.reshape(4, -1)  # reshape to 4_6 (row by row)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [160]:
a3_0.reshape(4, -1, order='F')  # reshape (column by column)

array([[ 1,  9,  6,  3, 11,  8],
       [13, 21, 18, 15, 23, 20],
       [ 5,  2, 10,  7,  4, 12],
       [17, 14, 22, 19, 16, 24]])

In [161]:
a3_0.reshape(4, 2, 3)  # reshape to 4_2_3 (row by row)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

## 12- 배열의 전치(transpose)

In [162]:
# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
# 행렬을 전치합니다.
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

-----------------------------------------------------------------------------------

# 데이터 구조의 이해 - (2) 데이터프레임

## 1- Titanic Features 변수명 설명
- survival:	Survival (0 = No; 1 = Yes)
- pclass: Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
- name: Name
- sex: Sex
- age: Age
- sibsp: Number of Siblings/Spouses Aboard
- parch: Number of Parents/Children Aboard
- ticket: Ticket Number
- fare: Passenger Fare
- cabin: Cabin
- embarked: Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)